[package]
name = "vp6-dec-rs"
version = "0.1.0"
authors = ["TÖRÖK Attila <torokati44@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[build-dependencies]
cc = "*"
pkg-config = "*"
