name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test Rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust_version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        rust_version: ['stable', 'beta', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_version }}
        override: true
        components: rustfmt, clippy
        target: wasm32-unknown-unknown

    - name: Add msys to PATH for clang
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all --all-features --tests -- -D warnings

    # wasm-bindgen-cli version must match wasm-bindgen crate version.
    # Be sure to update in release_nightly.yml, web/Cargo.toml and web/README.md.
    - name: Install wasm-bindgen
      run: cargo install wasm-bindgen-cli --version 0.2.76

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: binaryen

    # conda is available only with "shell: bash -l {0}".
    # See https://github.com/marketplace/actions/setup-miniconda.
    - name: Install binaryen
      shell: bash -l {0}
      run: conda install -c conda-forge binaryen

    - name: Install clang and binutils
      if: matrix.os == 'macOS-latest'
      shell: bash -l {0}
      run: conda install -c conda-forge clang binutils llvm-tools

    - name: Native build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features

    - name: Web build on macOS
      if: matrix.os == 'macOS-latest'
      shell: bash -l {0}
      env:
        AR: llvm-ar
      run: cargo build --target wasm32-unknown-unknown --all-features

    - name: Web build on non-macOS
      if: matrix.os != 'macOS-latest'
      shell: bash -l {0}
      run: cargo build --target wasm32-unknown-unknown --all-features

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features

    # TODO: add wasm-bindgen and wasm-opt invocations

